### ISSUE TITLE
Actualizar Contacto[Vista+Implementación]

### ISSUE THREAD

**Issue by adriancapchaq** [CONOVATEC-publico/Agenda#6]
Se puede editar todos los campos del contacto menos su id

**Comment by ETERRAZAS21PE** [comment]
# Estuve analizando la función que no pude completar, noté que el id en test.py está como string y debería estar con integer a fin de agregar un contador. 
# Método para añadir contacto

contacto = {}
def agregar():
    global contacto
    contacto = {
        "id":contacto.get('id'),
        "nombre":contacto.get('nombre'),
        "apellido":contacto.get('apellido'),
        "telefono":contacto.get('telefono')
        }
    contacto["id"] += 1

agregar()

**Comment by adriancapchaq** [comment]
en tu método estas volviendo a agregar lo que ya estaba guardado por que ese get trae el valor anterior, la idea es agregar uno nuevo
